SUPABASE_URL = "https://fquudfxkybqylcgtbbin.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdXVkZnhreWJxeWxjZ3RiYmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNjE4MDYsImV4cCI6MjA3OTgzNzgwNn0.Wf5i2KEvzWXj3dwsY5HxBOp3AcOX82h6WytZ0bH3dHg"
